# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='funding_status',
            field=models.CharField(choices=[('well_funded', 'Well Funded'), ('self_funded', 'Self Funded'), ('no_funding', 'No Funding'), ('unknown', 'Unknown')], max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_status_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='needs',
            field=models.TextField(blank=True),
        ),
    ]
