# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:47
from __future__ import unicode_literals
from django.db import migrations
import csv
from django.conf import settings


def import_spreadsheet(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    with open(str(settings.ROOT_DIR) + "/spreadsheet.csv") as csvfile:
        spamreader = csv.reader(csvfile, delimiter=',', quotechar='"')
        for row in spamreader:
            name = row[0]
            if not Project.objects.filter(name=name).exists():
                p = Project(
                    name=row[0],
                    website=row[1],
                    languages=[line.strip() for line in row[2].split(",")],
                    function=row[3],
                    maintainers=[line.strip() for line in row[4].split(",")],
                    added=row[5],
                    needs=row[6],
                    funding_status="unknown", # no way to auto-cover that
                    funding_status_notes=row[7]
                )

                p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160120_1046'),
    ]

    operations = [
        migrations.RunPython(import_spreadsheet),
    ]
