# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-21 10:00
from __future__ import unicode_literals

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20160120_1357'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 1, 21, 10, 0, 47, 348073, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='added',
            field=models.CharField(help_text='Who Added This (your GitHub, email, Twitter, etc)', max_length=100),
        ),
        migrations.AlterField(
            model_name='project',
            name='languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Primary Language or Community. (seperate, with, comma)', size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='maintainers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), help_text='Name a Maintainer (GitHub, email, Twitter etc. seperate, with, comma)', size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='needs',
            field=models.TextField(blank=True, help_text="Add'l Notes on Project Needs (1 sentence or less)"),
        ),
    ]
