# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 08:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_auto_20160121_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='function',
            field=models.TextField(blank=True),
        ),
    ]
