# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-22 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_auto_20160122_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='license',
            field=models.CharField(choices=[('apache_2', 'Apache 2.0'), ('bsd_3', 'BSD 3-Clause (New)'), ('bsd_2', 'BSD 2-Clause (FreeBSD)'), ('gpl', 'GPL'), ('lgpl', 'LGPL'), ('mit', 'MIT'), ('mpl', 'Mozilla Public License 2.0'), ('epl', 'Eclipse Public License'), ('unknown', 'Unknown'), ('other', 'Other')], default='unknown', max_length=20),
        ),
    ]
