# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 09:21
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='funding_type',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('corporate', 'Corporate'), ('individual', 'Individual'), ('foundation', 'Foundation'), ('academia', 'Academia'), ('consulting_services', 'Consulting/Services')], max_length=30), blank=True, default=[], help_text='Where do you receive funding from? (Leave empty if no funding)', size=None),
        ),
        migrations.AlterField(
            model_name='project',
            name='funding_status',
            field=models.CharField(choices=[('well_funded', 'Well Funded'), ('somewhat_funded', 'Somewhat funded'), ('no_funding', 'No Funding'), ('unknown', 'Unknown')], max_length=20),
        ),
    ]
