# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 10:22
from __future__ import unicode_literals

from django.db import migrations


def migrate_self_funded_to_no_funding(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.filter(funding_status="self_funded"):
        project.funding_status = "no_funding"
        project.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_auto_20160204_0921'),
    ]

    operations = [
        migrations.RunPython(migrate_self_funded_to_no_funding)
    ]
